source: aws

mappings:
  - name: ec2_compute_usage_v1
    version: 1

    schema_signature:
      - currency:string
      - resource_id:string
      - unblended_cost:string
      - usage_amount:string
      - usage_started_at:string
      - usage_unit:string

    static_fields:
      category: cloud
      service: ec2
      usage_type: compute_time

    fields:
      resource:
        - operation: copy
          from: payload.resource_id

      quantity:
        - operation: copy
          from: payload.usage_amount
        - operation: cast
          to: float

      unit:
        - operation: copy
          from: payload.usage_unit

      cost:
        - operation: copy
          from: payload.unblended_cost
        - operation: cast
          to: float

      currency:
        - operation: copy
          from: payload.currency

      usage_start:
        - operation: copy
          from: payload.usage_started_at
