"""Application paths and configuration locations."""

import os
from pathlib import Path

PROJECT_DIRECTORY = Path(__file__).resolve().parent.parent
CONFIG_DIRECTORY = PROJECT_DIRECTORY / "config"
DATA_DIRECTORY = PROJECT_DIRECTORY / "data"
DATABASE_PATH = DATA_DIRECTORY / "usage.db"
SQLITE_BUSY_TIMEOUT_MS = 5000
NORMALIZED_EVENT_SCHEMA_PATH = CONFIG_DIRECTORY / "normalized_event_schema.json"
AI_CONFIG_PATH = CONFIG_DIRECTORY / "ai.json"
MAPPINGS_DIRECTORY = CONFIG_DIRECTORY / "mappings"
PREDEFINED_MAPPINGS_DIRECTORY = MAPPINGS_DIRECTORY / "predefined"
GENERATED_MAPPINGS_DIRECTORY = MAPPINGS_DIRECTORY / "generated"
SUPPORTED_SOURCES = frozenset({"openai", "aws"})
KAFKA_BOOTSTRAP_SERVERS = os.getenv(
    "KAFKA_BOOTSTRAP_SERVERS",
    "localhost:9092",
)
KAFKA_DELIVERY_TIMEOUT_MS = 10_000
KAFKA_HEALTH_TIMEOUT_SECONDS = 5.0
